# Project: Comb1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = combMain.o md5.o writing.o hash1.o randomWordGen.o
LINKOBJ  = combMain.o md5.o writing.o hash1.o randomWordGen.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Comb1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

combMain.o: combMain.cpp
	$(CPP) -c combMain.cpp -o combMain.o $(CXXFLAGS)

md5.o: md5.cpp
	$(CPP) -c md5.cpp -o md5.o $(CXXFLAGS)

writing.o: writing.cpp
	$(CPP) -c writing.cpp -o writing.o $(CXXFLAGS)

hash1.o: hash1.cpp
	$(CPP) -c hash1.cpp -o hash1.o $(CXXFLAGS)

randomWordGen.o: randomWordGen.cpp
	$(CPP) -c randomWordGen.cpp -o randomWordGen.o $(CXXFLAGS)
